apiVersion: apps/v1


kind: ReplicaSet


metadata:
  name: myapp-replicaset

spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx-2
  template:
    metadata:
      labels:
        app: nginx-2
    spec:
      containers:
      - name: nginx
        image: nginx:latest
      
