apiVersion: v1




kind: Service



metadata:
  name: db
  labels:
    name: postgres-service
    app: demo-voting-app



spec:
  ports:
    - port: 5432            # Corrected from 'ports' to 'port'
      targetPort: 5432       # Corrected from 'targetport' to 'targetPort'
  selector:
    name: postgress-pod
    app: demo-voting-app
