apiVersion: v1



kind: Service



metadata:
  name: redis
  labels:
    app: demo-voting-app



spec:
  ports:
    - port: 6379            # Corrected from 'ports' to 'port'
      targetPort: 6379       # Corrected from 'targetport' to 'targetPort'
  selector:
    app: demo-voting-app
    name: redis-pod
